# GCP cloud overlay for Velero
# Use GCS for backup metadata/data movement and GCE PD snapshots for CSI movement.

credentials:
  useSecret: false

initContainers:
  - name: velero-plugin-for-gcp
    image: velero/velero-plugin-for-gcp:v1.11.0
    imagePullPolicy: IfNotPresent
    volumeMounts:
      - mountPath: /target
        name: plugins

configuration:
  backupStorageLocations:
    - name: default
      spec:
        provider: gcp
        default: true
        objectStorage:
          bucket: velero-backups
        accessMode: ReadWrite
  volumeSnapshotLocations:
    - name: default
      spec:
        provider: gcp
        config:
          project: ""
          snapshotLocation: ""

defaultVolumesToFsBackup: false
