# AWS cloud overlay for Velero
# Use S3 for backup metadata/data movement and EBS snapshots for CSI movement.

credentials:
  useSecret: false

initContainers:
  - name: velero-plugin-for-aws
    image: velero/velero-plugin-for-aws:v1.11.0
    imagePullPolicy: IfNotPresent
    volumeMounts:
      - mountPath: /target
        name: plugins

configuration:
  backupStorageLocation:
    - name: default
      provider: aws
      bucket: velero-backups
      default: true
      accessMode: ReadWrite
      config:
        region: eu-west-1
  volumeSnapshotLocation:
    - name: default
      provider: aws
      config:
        region: eu-west-1

defaultVolumesToFsBackup: false
