# OVH cloud overlay for Loki
# S3-compatible Object Storage via OVH Object Storage.

loki:
  storage:
    type: s3
    bucketNames:
      chunks: YOUR-CLUSTER-NAME-loki-chunks
      ruler: YOUR-CLUSTER-NAME-loki-ruler
    s3:
      endpoint: s3.gra.perf.cloud.ovh.net
      region: gra
      s3ForcePathStyle: true
  storage_config:
    aws:
      s3forcepathstyle: true
      endpoint: https://s3.gra.perf.cloud.ovh.net
      region: gra
  compactor:
    delete_request_store: s3

singleBinary:
  extraEnv:
    - name: AWS_ACCESS_KEY_ID
      valueFrom:
        secretKeyRef:
          name: loki-storage-credentials
          key: AWS_ACCESS_KEY_ID
    - name: AWS_SECRET_ACCESS_KEY
      valueFrom:
        secretKeyRef:
          name: loki-storage-credentials
          key: AWS_SECRET_ACCESS_KEY
